# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T10:10:06+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel, constr


class AccountId(RootModel[str]):
    root: str


class ActorDoesNotExistException(RootModel[Any]):
    root: Any


class AdditionalData(RootModel[str]):
    root: str


class ApprovalRuleContent(RootModel[constr(min_length=1, max_length=3000)]):
    root: constr(min_length=1, max_length=3000)


class ApprovalRuleContentRequiredException(RootModel[Any]):
    root: Any


class ApprovalRuleDoesNotExistException(RootModel[Any]):
    root: Any


class ApprovalRuleId(RootModel[str]):
    root: str


class ApprovalRuleName(RootModel[constr(min_length=1, max_length=100)]):
    root: constr(min_length=1, max_length=100)


class ApprovalRuleNameAlreadyExistsException(RootModel[Any]):
    root: Any


class ApprovalRuleNameRequiredException(RootModel[Any]):
    root: Any


class ApprovalRuleTemplateContent(RootModel[constr(min_length=1, max_length=3000)]):
    root: constr(min_length=1, max_length=3000)


class ApprovalRuleTemplateContentRequiredException(RootModel[Any]):
    root: Any


class ApprovalRuleTemplateDescription(RootModel[constr(min_length=0, max_length=1000)]):
    root: constr(min_length=0, max_length=1000)


class ApprovalRuleTemplateDoesNotExistException(RootModel[Any]):
    root: Any


class ApprovalRuleTemplateId(RootModel[str]):
    root: str


class ApprovalRuleTemplateInUseException(RootModel[Any]):
    root: Any


class ApprovalRuleTemplateName(RootModel[constr(min_length=1, max_length=100)]):
    root: constr(min_length=1, max_length=100)


class ApprovalRuleTemplateNameAlreadyExistsException(RootModel[Any]):
    root: Any


class ApprovalRuleTemplateNameList(RootModel[List[ApprovalRuleTemplateName]]):
    root: List[ApprovalRuleTemplateName]


class ApprovalRuleTemplateNameRequiredException(RootModel[Any]):
    root: Any


class ApprovalRulesNotSatisfiedList(RootModel[List[ApprovalRuleName]]):
    root: List[ApprovalRuleName]


class ApprovalRulesSatisfiedList(RootModel[List[ApprovalRuleName]]):
    root: List[ApprovalRuleName]


class ApprovalState(Enum):
    APPROVE = 'APPROVE'
    REVOKE = 'REVOKE'


class ApprovalStateRequiredException(RootModel[Any]):
    root: Any


class Approved(RootModel[bool]):
    root: bool


class Arn(RootModel[str]):
    root: str


class AuthorDoesNotExistException(RootModel[Any]):
    root: Any


class BeforeCommitIdAndAfterCommitIdAreSameException(RootModel[Any]):
    root: Any


class BlobIdDoesNotExistException(RootModel[Any]):
    root: Any


class BlobIdRequiredException(RootModel[Any]):
    root: Any


class BranchDoesNotExistException(RootModel[Any]):
    root: Any


class BranchName(RootModel[constr(min_length=1, max_length=256)]):
    root: constr(min_length=1, max_length=256)


class BranchNameExistsException(RootModel[Any]):
    root: Any


class BranchNameIsTagNameException(RootModel[Any]):
    root: Any


class BranchNameList(RootModel[List[BranchName]]):
    root: List[BranchName]


class BranchNameRequiredException(RootModel[Any]):
    root: Any


class CannotDeleteApprovalRuleFromTemplateException(RootModel[Any]):
    root: Any


class CannotModifyApprovalRuleFromTemplateException(RootModel[Any]):
    root: Any


class CapitalBoolean(RootModel[bool]):
    root: bool


class ChangeTypeEnum(Enum):
    A = 'A'
    M = 'M'
    D = 'D'


class ClientRequestToken(RootModel[str]):
    root: str


class ClientRequestTokenRequiredException(RootModel[Any]):
    root: Any


class CloneUrlHttp(RootModel[str]):
    root: str


class CloneUrlSsh(RootModel[str]):
    root: str


class CommentContentRequiredException(RootModel[Any]):
    root: Any


class CommentContentSizeLimitExceededException(RootModel[Any]):
    root: Any


class CommentDeletedException(RootModel[Any]):
    root: Any


class CommentDoesNotExistException(RootModel[Any]):
    root: Any


class CommentId(RootModel[str]):
    root: str


class CommentIdRequiredException(RootModel[Any]):
    root: Any


class CommentNotCreatedByCallerException(RootModel[Any]):
    root: Any


class CommitDoesNotExistException(RootModel[Any]):
    root: Any


class CommitId(RootModel[str]):
    root: str


class CommitIdDoesNotExistException(RootModel[Any]):
    root: Any


class CommitIdRequiredException(RootModel[Any]):
    root: Any


class CommitIdsLimitExceededException(RootModel[Any]):
    root: Any


class CommitIdsListRequiredException(RootModel[Any]):
    root: Any


class CommitMessageLengthExceededException(RootModel[Any]):
    root: Any


class CommitName(RootModel[str]):
    root: str


class CommitRequiredException(RootModel[Any]):
    root: Any


class ConcurrentReferenceUpdateException(RootModel[Any]):
    root: Any


class ConflictDetailLevelTypeEnum(Enum):
    FILE_LEVEL = 'FILE_LEVEL'
    LINE_LEVEL = 'LINE_LEVEL'


class ConflictResolutionStrategyTypeEnum(Enum):
    NONE = 'NONE'
    ACCEPT_SOURCE = 'ACCEPT_SOURCE'
    ACCEPT_DESTINATION = 'ACCEPT_DESTINATION'
    AUTOMERGE = 'AUTOMERGE'


class Content(RootModel[str]):
    root: str


class Count(RootModel[int]):
    root: int


class CreateApprovalRuleTemplateInput(BaseModel):
    approvalRuleTemplateContent: ApprovalRuleTemplateContent
    approvalRuleTemplateDescription: Optional[ApprovalRuleTemplateDescription] = None
    approvalRuleTemplateName: ApprovalRuleTemplateName


class CreationDate(RootModel[datetime]):
    root: datetime


class Date(RootModel[str]):
    root: str


class DefaultBranchCannotBeDeletedException(RootModel[Any]):
    root: Any


class DeleteApprovalRuleTemplateInput(BaseModel):
    approvalRuleTemplateName: ApprovalRuleTemplateName


class DeleteApprovalRuleTemplateOutput(BaseModel):
    approvalRuleTemplateId: ApprovalRuleTemplateId


class DeleteCommentContentInput(BaseModel):
    commentId: CommentId


class DeletePullRequestApprovalRuleOutput(BaseModel):
    approvalRuleId: ApprovalRuleId


class Description(RootModel[constr(max_length=10240)]):
    root: constr(max_length=10240)


class DirectoryNameConflictsWithFileNameException(RootModel[Any]):
    root: Any


class Email(RootModel[str]):
    root: str


class EncryptionIntegrityChecksFailedException(RootModel[Any]):
    root: Any


class EncryptionKeyAccessDeniedException(RootModel[Any]):
    root: Any


class EncryptionKeyDisabledException(RootModel[Any]):
    root: Any


class EncryptionKeyNotFoundException(RootModel[Any]):
    root: Any


class EncryptionKeyUnavailableException(RootModel[Any]):
    root: Any


class ErrorCode(RootModel[str]):
    root: str


class ErrorMessage(RootModel[str]):
    root: str


class EventDate(RootModel[datetime]):
    root: datetime


class ExceptionName(RootModel[str]):
    root: str


class FileContent(RootModel[constr(max_length=6291456)]):
    root: constr(max_length=6291456)


class FileContentAndSourceFileSpecifiedException(RootModel[Any]):
    root: Any


class FileContentRequiredException(RootModel[Any]):
    root: Any


class FileContentSizeLimitExceededException(RootModel[Any]):
    root: Any


class FileDoesNotExistException(RootModel[Any]):
    root: Any


class FileEntryRequiredException(RootModel[Any]):
    root: Any


class FileModeRequiredException(RootModel[Any]):
    root: Any


class FileModeTypeEnum(Enum):
    EXECUTABLE = 'EXECUTABLE'
    NORMAL = 'NORMAL'
    SYMLINK = 'SYMLINK'


class FileModes(BaseModel):
    base: Optional[FileModeTypeEnum] = None
    destination: Optional[FileModeTypeEnum] = None
    source: Optional[FileModeTypeEnum] = None


class FileNameConflictsWithDirectoryNameException(RootModel[Any]):
    root: Any


class FilePathConflictsWithSubmodulePathException(RootModel[Any]):
    root: Any


class FileSize(RootModel[int]):
    root: int


class FileSizes(BaseModel):
    base: Optional[FileSize] = None
    destination: Optional[FileSize] = None
    source: Optional[FileSize] = None


class FileTooLargeException(RootModel[Any]):
    root: Any


class FolderContentSizeLimitExceededException(RootModel[Any]):
    root: Any


class FolderDoesNotExistException(RootModel[Any]):
    root: Any


class GetApprovalRuleTemplateInput(BaseModel):
    approvalRuleTemplateName: ApprovalRuleTemplateName


class GetCommentInput(BaseModel):
    commentId: CommentId


class HunkContent(RootModel[str]):
    root: str


class IdempotencyParameterMismatchException(RootModel[Any]):
    root: Any


class InvalidActorArnException(RootModel[Any]):
    root: Any


class InvalidApprovalRuleContentException(RootModel[Any]):
    root: Any


class InvalidApprovalRuleNameException(RootModel[Any]):
    root: Any


class InvalidApprovalRuleTemplateContentException(RootModel[Any]):
    root: Any


class InvalidApprovalRuleTemplateDescriptionException(RootModel[Any]):
    root: Any


class InvalidApprovalRuleTemplateNameException(RootModel[Any]):
    root: Any


class InvalidApprovalStateException(RootModel[Any]):
    root: Any


class InvalidAuthorArnException(RootModel[Any]):
    root: Any


class InvalidBlobIdException(RootModel[Any]):
    root: Any


class InvalidBranchNameException(RootModel[Any]):
    root: Any


class InvalidClientRequestTokenException(RootModel[Any]):
    root: Any


class InvalidCommentIdException(RootModel[Any]):
    root: Any


class InvalidCommitException(RootModel[Any]):
    root: Any


class InvalidCommitIdException(RootModel[Any]):
    root: Any


class InvalidConflictDetailLevelException(RootModel[Any]):
    root: Any


class InvalidConflictResolutionException(RootModel[Any]):
    root: Any


class InvalidConflictResolutionStrategyException(RootModel[Any]):
    root: Any


class InvalidContinuationTokenException(RootModel[Any]):
    root: Any


class InvalidDeletionParameterException(RootModel[Any]):
    root: Any


class InvalidDescriptionException(RootModel[Any]):
    root: Any


class InvalidDestinationCommitSpecifierException(RootModel[Any]):
    root: Any


class InvalidEmailException(RootModel[Any]):
    root: Any


class InvalidFileLocationException(RootModel[Any]):
    root: Any


class InvalidFileModeException(RootModel[Any]):
    root: Any


class InvalidFilePositionException(RootModel[Any]):
    root: Any


class InvalidMaxConflictFilesException(RootModel[Any]):
    root: Any


class InvalidMaxMergeHunksException(RootModel[Any]):
    root: Any


class InvalidMaxResultsException(RootModel[Any]):
    root: Any


class InvalidMergeOptionException(RootModel[Any]):
    root: Any


class InvalidOrderException(RootModel[Any]):
    root: Any


class InvalidOverrideStatusException(RootModel[Any]):
    root: Any


class InvalidParentCommitIdException(RootModel[Any]):
    root: Any


class InvalidPathException(RootModel[Any]):
    root: Any


class InvalidPullRequestEventTypeException(RootModel[Any]):
    root: Any


class InvalidPullRequestIdException(RootModel[Any]):
    root: Any


class InvalidPullRequestStatusException(RootModel[Any]):
    root: Any


class InvalidPullRequestStatusUpdateException(RootModel[Any]):
    root: Any


class InvalidReactionUserArnException(RootModel[Any]):
    root: Any


class InvalidReactionValueException(RootModel[Any]):
    root: Any


class InvalidReferenceNameException(RootModel[Any]):
    root: Any


class InvalidRelativeFileVersionEnumException(RootModel[Any]):
    root: Any


class InvalidReplacementContentException(RootModel[Any]):
    root: Any


class InvalidReplacementTypeException(RootModel[Any]):
    root: Any


class InvalidRepositoryDescriptionException(RootModel[Any]):
    root: Any


class InvalidRepositoryNameException(RootModel[Any]):
    root: Any


class InvalidRepositoryTriggerBranchNameException(RootModel[Any]):
    root: Any


class InvalidRepositoryTriggerCustomDataException(RootModel[Any]):
    root: Any


class InvalidRepositoryTriggerDestinationArnException(RootModel[Any]):
    root: Any


class InvalidRepositoryTriggerEventsException(RootModel[Any]):
    root: Any


class InvalidRepositoryTriggerNameException(RootModel[Any]):
    root: Any


class InvalidRepositoryTriggerRegionException(RootModel[Any]):
    root: Any


class InvalidResourceArnException(RootModel[Any]):
    root: Any


class InvalidRevisionIdException(RootModel[Any]):
    root: Any


class InvalidRuleContentSha256Exception(RootModel[Any]):
    root: Any


class InvalidSortByException(RootModel[Any]):
    root: Any


class InvalidSourceCommitSpecifierException(RootModel[Any]):
    root: Any


class InvalidSystemTagUsageException(RootModel[Any]):
    root: Any


class InvalidTagKeysListException(RootModel[Any]):
    root: Any


class InvalidTagsMapException(RootModel[Any]):
    root: Any


class InvalidTargetBranchException(RootModel[Any]):
    root: Any


class InvalidTargetException(RootModel[Any]):
    root: Any


class InvalidTargetsException(RootModel[Any]):
    root: Any


class InvalidTitleException(RootModel[Any]):
    root: Any


class IsBinaryFile(BaseModel):
    base: Optional[CapitalBoolean] = None
    destination: Optional[CapitalBoolean] = None
    source: Optional[CapitalBoolean] = None


class IsCommentDeleted(RootModel[bool]):
    root: bool


class IsContentConflict(RootModel[bool]):
    root: bool


class IsFileModeConflict(RootModel[bool]):
    root: bool


class IsHunkConflict(RootModel[bool]):
    root: bool


class IsMergeable(RootModel[bool]):
    root: bool


class IsMerged(RootModel[bool]):
    root: bool


class IsMove(RootModel[bool]):
    root: bool


class IsObjectTypeConflict(RootModel[bool]):
    root: bool


class KeepEmptyFolders(RootModel[bool]):
    root: bool


class LastModifiedDate(RootModel[datetime]):
    root: datetime


class Limit(RootModel[int]):
    root: int


class LineNumber(RootModel[int]):
    root: int


class ManualMergeRequiredException(RootModel[Any]):
    root: Any


class MaxResults(RootModel[int]):
    root: int


class MaximumBranchesExceededException(RootModel[Any]):
    root: Any


class MaximumConflictResolutionEntriesExceededException(RootModel[Any]):
    root: Any


class MaximumFileContentToLoadExceededException(RootModel[Any]):
    root: Any


class MaximumFileEntriesExceededException(RootModel[Any]):
    root: Any


class MaximumItemsToCompareExceededException(RootModel[Any]):
    root: Any


class MaximumNumberOfApprovalsExceededException(RootModel[Any]):
    root: Any


class MaximumOpenPullRequestsExceededException(RootModel[Any]):
    root: Any


class MaximumRepositoryNamesExceededException(RootModel[Any]):
    root: Any


class MaximumRepositoryTriggersExceededException(RootModel[Any]):
    root: Any


class MaximumRuleTemplatesAssociatedWithRepositoryException(RootModel[Any]):
    root: Any


class MergeHunkDetail(BaseModel):
    endLine: Optional[LineNumber] = None
    hunkContent: Optional[HunkContent] = None
    startLine: Optional[LineNumber] = None


class MergeOperations(BaseModel):
    destination: Optional[ChangeTypeEnum] = None
    source: Optional[ChangeTypeEnum] = None


class MergeOptionRequiredException(RootModel[Any]):
    root: Any


class MergeOptionTypeEnum(Enum):
    FAST_FORWARD_MERGE = 'FAST_FORWARD_MERGE'
    SQUASH_MERGE = 'SQUASH_MERGE'
    THREE_WAY_MERGE = 'THREE_WAY_MERGE'


class MergeOptions(RootModel[List[MergeOptionTypeEnum]]):
    root: List[MergeOptionTypeEnum]


class Message(RootModel[str]):
    root: str


class Mode(RootModel[str]):
    root: str


class MultipleConflictResolutionEntriesException(RootModel[Any]):
    root: Any


class MultipleRepositoriesInPullRequestException(RootModel[Any]):
    root: Any


class Name(RootModel[str]):
    root: str


class NameLengthExceededException(RootModel[Any]):
    root: Any


class NextToken(RootModel[str]):
    root: str


class NoChangeException(RootModel[Any]):
    root: Any


class NumberOfConflicts(RootModel[int]):
    root: int


class NumberOfRuleTemplatesExceededException(RootModel[Any]):
    root: Any


class NumberOfRulesExceededException(RootModel[Any]):
    root: Any


class ObjectId(RootModel[str]):
    root: str


class ObjectSize(RootModel[int]):
    root: int


class ObjectTypeEnum(Enum):
    FILE = 'FILE'
    DIRECTORY = 'DIRECTORY'
    GIT_LINK = 'GIT_LINK'
    SYMBOLIC_LINK = 'SYMBOLIC_LINK'


class ObjectTypes(BaseModel):
    base: Optional[ObjectTypeEnum] = None
    destination: Optional[ObjectTypeEnum] = None
    source: Optional[ObjectTypeEnum] = None


class OrderEnum(Enum):
    ascending = 'ascending'
    descending = 'descending'


class OriginApprovalRuleTemplate(BaseModel):
    approvalRuleTemplateId: Optional[ApprovalRuleTemplateId] = None
    approvalRuleTemplateName: Optional[ApprovalRuleTemplateName] = None


class Overridden(RootModel[bool]):
    root: bool


class OverrideAlreadySetException(RootModel[Any]):
    root: Any


class OverrideStatus(Enum):
    OVERRIDE = 'OVERRIDE'
    REVOKE = 'REVOKE'


class OverrideStatusRequiredException(RootModel[Any]):
    root: Any


class ParentCommitDoesNotExistException(RootModel[Any]):
    root: Any


class ParentCommitIdOutdatedException(RootModel[Any]):
    root: Any


class ParentCommitIdRequiredException(RootModel[Any]):
    root: Any


class ParentList(RootModel[List[ObjectId]]):
    root: List[ObjectId]


class Path(RootModel[str]):
    root: str


class PathDoesNotExistException(RootModel[Any]):
    root: Any


class PathRequiredException(RootModel[Any]):
    root: Any


class Position(RootModel[int]):
    root: int


class PostCommentReplyInput(BaseModel):
    clientRequestToken: Optional[ClientRequestToken] = None
    content: Content
    inReplyTo: CommentId


class PullRequestAlreadyClosedException(RootModel[Any]):
    root: Any


class PullRequestApprovalRulesNotSatisfiedException(RootModel[Any]):
    root: Any


class PullRequestCannotBeApprovedByAuthorException(RootModel[Any]):
    root: Any


class PullRequestDoesNotExistException(RootModel[Any]):
    root: Any


class PullRequestEventType(Enum):
    PULL_REQUEST_CREATED = 'PULL_REQUEST_CREATED'
    PULL_REQUEST_STATUS_CHANGED = 'PULL_REQUEST_STATUS_CHANGED'
    PULL_REQUEST_SOURCE_REFERENCE_UPDATED = 'PULL_REQUEST_SOURCE_REFERENCE_UPDATED'
    PULL_REQUEST_MERGE_STATE_CHANGED = 'PULL_REQUEST_MERGE_STATE_CHANGED'
    PULL_REQUEST_APPROVAL_RULE_CREATED = 'PULL_REQUEST_APPROVAL_RULE_CREATED'
    PULL_REQUEST_APPROVAL_RULE_UPDATED = 'PULL_REQUEST_APPROVAL_RULE_UPDATED'
    PULL_REQUEST_APPROVAL_RULE_DELETED = 'PULL_REQUEST_APPROVAL_RULE_DELETED'
    PULL_REQUEST_APPROVAL_RULE_OVERRIDDEN = 'PULL_REQUEST_APPROVAL_RULE_OVERRIDDEN'
    PULL_REQUEST_APPROVAL_STATE_CHANGED = 'PULL_REQUEST_APPROVAL_STATE_CHANGED'


class PullRequestId(RootModel[str]):
    root: str


class PullRequestIdList(RootModel[List[PullRequestId]]):
    root: List[PullRequestId]


class PullRequestIdRequiredException(RootModel[Any]):
    root: Any


class PullRequestStatusEnum(Enum):
    OPEN = 'OPEN'
    CLOSED = 'CLOSED'


class PullRequestStatusRequiredException(RootModel[Any]):
    root: Any


class PutFileEntryConflictException(RootModel[Any]):
    root: Any


class PutFileOutput(BaseModel):
    blobId: ObjectId
    commitId: ObjectId
    treeId: ObjectId


class ReactionCountsMap(RootModel[Optional[Dict[str, Count]]]):
    root: Optional[Dict[str, Count]] = None


class ReactionEmoji(RootModel[str]):
    root: str


class ReactionLimitExceededException(RootModel[Any]):
    root: Any


class ReactionShortCode(RootModel[str]):
    root: str


class ReactionUnicode(RootModel[str]):
    root: str


class ReactionUsersList(RootModel[List[Arn]]):
    root: List[Arn]


class ReactionValue(RootModel[str]):
    root: str


class ReactionValueFormats(BaseModel):
    emoji: Optional[ReactionEmoji] = None
    shortCode: Optional[ReactionShortCode] = None
    unicode: Optional[ReactionUnicode] = None


class ReactionValueRequiredException(RootModel[Any]):
    root: Any


class ReferenceDoesNotExistException(RootModel[Any]):
    root: Any


class ReferenceName(RootModel[str]):
    root: str


class ReferenceNameRequiredException(RootModel[Any]):
    root: Any


class ReferenceTypeNotSupportedException(RootModel[Any]):
    root: Any


class RelativeFileVersionEnum(Enum):
    BEFORE = 'BEFORE'
    AFTER = 'AFTER'


class ReplacementContentRequiredException(RootModel[Any]):
    root: Any


class ReplacementTypeEnum(Enum):
    KEEP_BASE = 'KEEP_BASE'
    KEEP_SOURCE = 'KEEP_SOURCE'
    KEEP_DESTINATION = 'KEEP_DESTINATION'
    USE_NEW_CONTENT = 'USE_NEW_CONTENT'


class ReplacementTypeRequiredException(RootModel[Any]):
    root: Any


class RepositoryDescription(RootModel[constr(max_length=1000)]):
    root: constr(max_length=1000)


class RepositoryDoesNotExistException(RootModel[Any]):
    root: Any


class RepositoryId(RootModel[str]):
    root: str


class RepositoryLimitExceededException(RootModel[Any]):
    root: Any


class RepositoryName(
    RootModel[constr(pattern=r'[\w\.-]+', min_length=1, max_length=100)]
):
    root: constr(pattern=r'[\w\.-]+', min_length=1, max_length=100)


class RepositoryNameExistsException(RootModel[Any]):
    root: Any


class RepositoryNameIdPair(BaseModel):
    repositoryId: Optional[RepositoryId] = None
    repositoryName: Optional[RepositoryName] = None


class RepositoryNameIdPairList(RootModel[List[RepositoryNameIdPair]]):
    root: List[RepositoryNameIdPair]


class RepositoryNameList(RootModel[List[RepositoryName]]):
    root: List[RepositoryName]


class RepositoryNameRequiredException(RootModel[Any]):
    root: Any


class RepositoryNamesRequiredException(RootModel[Any]):
    root: Any


class RepositoryNotAssociatedWithPullRequestException(RootModel[Any]):
    root: Any


class RepositoryNotFoundList(RootModel[List[RepositoryName]]):
    root: List[RepositoryName]


class RepositoryTriggerBranchNameListRequiredException(RootModel[Any]):
    root: Any


class RepositoryTriggerCustomData(RootModel[str]):
    root: str


class RepositoryTriggerDestinationArnRequiredException(RootModel[Any]):
    root: Any


class RepositoryTriggerEventEnum(Enum):
    all = 'all'
    updateReference = 'updateReference'
    createReference = 'createReference'
    deleteReference = 'deleteReference'


class RepositoryTriggerEventList(RootModel[List[RepositoryTriggerEventEnum]]):
    root: List[RepositoryTriggerEventEnum]


class RepositoryTriggerEventsListRequiredException(RootModel[Any]):
    root: Any


class RepositoryTriggerExecutionFailureMessage(RootModel[str]):
    root: str


class RepositoryTriggerName(RootModel[str]):
    root: str


class RepositoryTriggerNameList(RootModel[List[RepositoryTriggerName]]):
    root: List[RepositoryTriggerName]


class RepositoryTriggerNameRequiredException(RootModel[Any]):
    root: Any


class RepositoryTriggersConfigurationId(RootModel[str]):
    root: str


class RepositoryTriggersListRequiredException(RootModel[Any]):
    root: Any


class ResourceArn(RootModel[str]):
    root: str


class ResourceArnRequiredException(RootModel[Any]):
    root: Any


class RestrictedSourceFileException(RootModel[Any]):
    root: Any


class RevisionId(RootModel[str]):
    root: str


class RevisionIdRequiredException(RootModel[Any]):
    root: Any


class RevisionNotCurrentException(RootModel[Any]):
    root: Any


class RuleContentSha256(RootModel[str]):
    root: str


class SameFileContentException(RootModel[Any]):
    root: Any


class SamePathRequestException(RootModel[Any]):
    root: Any


class SetFileModeEntry(BaseModel):
    fileMode: FileModeTypeEnum
    filePath: Path


class SortByEnum(Enum):
    repositoryName = 'repositoryName'
    lastModifiedDate = 'lastModifiedDate'


class SourceAndDestinationAreSameException(RootModel[Any]):
    root: Any


class SourceFileOrContentRequiredException(RootModel[Any]):
    root: Any


class SourceFileSpecifier(BaseModel):
    filePath: Path
    isMove: Optional[IsMove] = None


class SubModule(BaseModel):
    absolutePath: Optional[Path] = None
    commitId: Optional[ObjectId] = None
    relativePath: Optional[Path] = None


class SubModuleList(RootModel[List[SubModule]]):
    root: List[SubModule]


class SymbolicLink(BaseModel):
    absolutePath: Optional[Path] = None
    blobId: Optional[ObjectId] = None
    fileMode: Optional[FileModeTypeEnum] = None
    relativePath: Optional[Path] = None


class SymbolicLinkList(RootModel[List[SymbolicLink]]):
    root: List[SymbolicLink]


class TagKey(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class TagKeysList(RootModel[List[TagKey]]):
    root: List[TagKey]


class TagKeysListRequiredException(RootModel[Any]):
    root: Any


class TagPolicyException(RootModel[Any]):
    root: Any


class TagValue(RootModel[constr(min_length=0, max_length=256)]):
    root: constr(min_length=0, max_length=256)


class TagsMap(RootModel[Optional[Dict[str, TagValue]]]):
    root: Optional[Dict[str, TagValue]] = None


class TagsMapRequiredException(RootModel[Any]):
    root: Any


class Target(BaseModel):
    destinationReference: Optional[ReferenceName] = None
    repositoryName: RepositoryName
    sourceReference: ReferenceName


class TargetList(RootModel[List[Target]]):
    root: List[Target]


class TargetRequiredException(RootModel[Any]):
    root: Any


class TargetsRequiredException(RootModel[Any]):
    root: Any


class TipOfSourceReferenceIsDifferentException(RootModel[Any]):
    root: Any


class TipsDivergenceExceededException(RootModel[Any]):
    root: Any


class Title(RootModel[constr(max_length=150)]):
    root: constr(max_length=150)


class TitleRequiredException(RootModel[Any]):
    root: Any


class TooManyTagsException(RootModel[Any]):
    root: Any


class UntagResourceInput(BaseModel):
    resourceArn: ResourceArn
    tagKeys: TagKeysList


class UpdateApprovalRuleTemplateContentInput(BaseModel):
    approvalRuleTemplateName: ApprovalRuleTemplateName
    existingRuleContentSha256: Optional[RuleContentSha256] = None
    newRuleContent: ApprovalRuleTemplateContent


class UpdateApprovalRuleTemplateDescriptionInput(BaseModel):
    approvalRuleTemplateDescription: ApprovalRuleTemplateDescription
    approvalRuleTemplateName: ApprovalRuleTemplateName


class UpdateApprovalRuleTemplateNameInput(BaseModel):
    newApprovalRuleTemplateName: ApprovalRuleTemplateName
    oldApprovalRuleTemplateName: ApprovalRuleTemplateName


class UpdateCommentInput(BaseModel):
    commentId: CommentId
    content: Content


class UpdateDefaultBranchInput(BaseModel):
    defaultBranchName: BranchName
    repositoryName: RepositoryName


class UpdatePullRequestApprovalRuleContentInput(BaseModel):
    approvalRuleName: ApprovalRuleName
    existingRuleContentSha256: Optional[RuleContentSha256] = None
    newRuleContent: ApprovalRuleContent
    pullRequestId: PullRequestId


class UpdatePullRequestApprovalStateInput(BaseModel):
    approvalState: ApprovalState
    pullRequestId: PullRequestId
    revisionId: RevisionId


class UpdatePullRequestDescriptionInput(BaseModel):
    description: Description
    pullRequestId: PullRequestId


class UpdatePullRequestStatusInput(BaseModel):
    pullRequestId: PullRequestId
    pullRequestStatus: PullRequestStatusEnum


class UpdatePullRequestTitleInput(BaseModel):
    pullRequestId: PullRequestId
    title: Title


class UpdateRepositoryDescriptionInput(BaseModel):
    repositoryDescription: Optional[RepositoryDescription] = None
    repositoryName: RepositoryName


class UpdateRepositoryNameInput(BaseModel):
    newName: RepositoryName
    oldName: RepositoryName


class UserInfo(BaseModel):
    date: Optional[Date] = None
    email: Optional[Email] = None
    name: Optional[Name] = None


class Blob(RootModel[str]):
    root: str


class XAmzTarget(Enum):
    CodeCommit_20150413_AssociateApprovalRuleTemplateWithRepository = (
        'CodeCommit_20150413.AssociateApprovalRuleTemplateWithRepository'
    )


class XAmzTarget1(Enum):
    CodeCommit_20150413_BatchAssociateApprovalRuleTemplateWithRepositories = (
        'CodeCommit_20150413.BatchAssociateApprovalRuleTemplateWithRepositories'
    )


class XAmzTarget2(Enum):
    CodeCommit_20150413_BatchDescribeMergeConflicts = (
        'CodeCommit_20150413.BatchDescribeMergeConflicts'
    )


class XAmzTarget3(Enum):
    CodeCommit_20150413_BatchDisassociateApprovalRuleTemplateFromRepositories = (
        'CodeCommit_20150413.BatchDisassociateApprovalRuleTemplateFromRepositories'
    )


class XAmzTarget4(Enum):
    CodeCommit_20150413_BatchGetCommits = 'CodeCommit_20150413.BatchGetCommits'


class XAmzTarget5(Enum):
    CodeCommit_20150413_BatchGetRepositories = (
        'CodeCommit_20150413.BatchGetRepositories'
    )


class XAmzTarget6(Enum):
    CodeCommit_20150413_CreateApprovalRuleTemplate = (
        'CodeCommit_20150413.CreateApprovalRuleTemplate'
    )


class XAmzTarget7(Enum):
    CodeCommit_20150413_CreateBranch = 'CodeCommit_20150413.CreateBranch'


class XAmzTarget8(Enum):
    CodeCommit_20150413_CreateCommit = 'CodeCommit_20150413.CreateCommit'


class XAmzTarget9(Enum):
    CodeCommit_20150413_CreatePullRequest = 'CodeCommit_20150413.CreatePullRequest'


class XAmzTarget10(Enum):
    CodeCommit_20150413_CreatePullRequestApprovalRule = (
        'CodeCommit_20150413.CreatePullRequestApprovalRule'
    )


class XAmzTarget11(Enum):
    CodeCommit_20150413_CreateRepository = 'CodeCommit_20150413.CreateRepository'


class XAmzTarget12(Enum):
    CodeCommit_20150413_CreateUnreferencedMergeCommit = (
        'CodeCommit_20150413.CreateUnreferencedMergeCommit'
    )


class XAmzTarget13(Enum):
    CodeCommit_20150413_DeleteApprovalRuleTemplate = (
        'CodeCommit_20150413.DeleteApprovalRuleTemplate'
    )


class XAmzTarget14(Enum):
    CodeCommit_20150413_DeleteBranch = 'CodeCommit_20150413.DeleteBranch'


class XAmzTarget15(Enum):
    CodeCommit_20150413_DeleteCommentContent = (
        'CodeCommit_20150413.DeleteCommentContent'
    )


class XAmzTarget16(Enum):
    CodeCommit_20150413_DeleteFile = 'CodeCommit_20150413.DeleteFile'


class XAmzTarget17(Enum):
    CodeCommit_20150413_DeletePullRequestApprovalRule = (
        'CodeCommit_20150413.DeletePullRequestApprovalRule'
    )


class XAmzTarget18(Enum):
    CodeCommit_20150413_DeleteRepository = 'CodeCommit_20150413.DeleteRepository'


class XAmzTarget19(Enum):
    CodeCommit_20150413_DescribeMergeConflicts = (
        'CodeCommit_20150413.DescribeMergeConflicts'
    )


class XAmzTarget20(Enum):
    CodeCommit_20150413_DescribePullRequestEvents = (
        'CodeCommit_20150413.DescribePullRequestEvents'
    )


class XAmzTarget21(Enum):
    CodeCommit_20150413_DisassociateApprovalRuleTemplateFromRepository = (
        'CodeCommit_20150413.DisassociateApprovalRuleTemplateFromRepository'
    )


class XAmzTarget22(Enum):
    CodeCommit_20150413_EvaluatePullRequestApprovalRules = (
        'CodeCommit_20150413.EvaluatePullRequestApprovalRules'
    )


class XAmzTarget23(Enum):
    CodeCommit_20150413_GetApprovalRuleTemplate = (
        'CodeCommit_20150413.GetApprovalRuleTemplate'
    )


class XAmzTarget24(Enum):
    CodeCommit_20150413_GetBlob = 'CodeCommit_20150413.GetBlob'


class XAmzTarget25(Enum):
    CodeCommit_20150413_GetBranch = 'CodeCommit_20150413.GetBranch'


class XAmzTarget26(Enum):
    CodeCommit_20150413_GetComment = 'CodeCommit_20150413.GetComment'


class XAmzTarget27(Enum):
    CodeCommit_20150413_GetCommentReactions = 'CodeCommit_20150413.GetCommentReactions'


class XAmzTarget28(Enum):
    CodeCommit_20150413_GetCommentsForComparedCommit = (
        'CodeCommit_20150413.GetCommentsForComparedCommit'
    )


class XAmzTarget29(Enum):
    CodeCommit_20150413_GetCommentsForPullRequest = (
        'CodeCommit_20150413.GetCommentsForPullRequest'
    )


class XAmzTarget30(Enum):
    CodeCommit_20150413_GetCommit = 'CodeCommit_20150413.GetCommit'


class XAmzTarget31(Enum):
    CodeCommit_20150413_GetDifferences = 'CodeCommit_20150413.GetDifferences'


class XAmzTarget32(Enum):
    CodeCommit_20150413_GetFile = 'CodeCommit_20150413.GetFile'


class XAmzTarget33(Enum):
    CodeCommit_20150413_GetFolder = 'CodeCommit_20150413.GetFolder'


class XAmzTarget34(Enum):
    CodeCommit_20150413_GetMergeCommit = 'CodeCommit_20150413.GetMergeCommit'


class XAmzTarget35(Enum):
    CodeCommit_20150413_GetMergeConflicts = 'CodeCommit_20150413.GetMergeConflicts'


class XAmzTarget36(Enum):
    CodeCommit_20150413_GetMergeOptions = 'CodeCommit_20150413.GetMergeOptions'


class XAmzTarget37(Enum):
    CodeCommit_20150413_GetPullRequest = 'CodeCommit_20150413.GetPullRequest'


class XAmzTarget38(Enum):
    CodeCommit_20150413_GetPullRequestApprovalStates = (
        'CodeCommit_20150413.GetPullRequestApprovalStates'
    )


class XAmzTarget39(Enum):
    CodeCommit_20150413_GetPullRequestOverrideState = (
        'CodeCommit_20150413.GetPullRequestOverrideState'
    )


class XAmzTarget40(Enum):
    CodeCommit_20150413_GetRepository = 'CodeCommit_20150413.GetRepository'


class XAmzTarget41(Enum):
    CodeCommit_20150413_GetRepositoryTriggers = (
        'CodeCommit_20150413.GetRepositoryTriggers'
    )


class XAmzTarget42(Enum):
    CodeCommit_20150413_ListApprovalRuleTemplates = (
        'CodeCommit_20150413.ListApprovalRuleTemplates'
    )


class XAmzTarget43(Enum):
    CodeCommit_20150413_ListAssociatedApprovalRuleTemplatesForRepository = (
        'CodeCommit_20150413.ListAssociatedApprovalRuleTemplatesForRepository'
    )


class XAmzTarget44(Enum):
    CodeCommit_20150413_ListBranches = 'CodeCommit_20150413.ListBranches'


class XAmzTarget45(Enum):
    CodeCommit_20150413_ListPullRequests = 'CodeCommit_20150413.ListPullRequests'


class XAmzTarget46(Enum):
    CodeCommit_20150413_ListRepositories = 'CodeCommit_20150413.ListRepositories'


class XAmzTarget47(Enum):
    CodeCommit_20150413_ListRepositoriesForApprovalRuleTemplate = (
        'CodeCommit_20150413.ListRepositoriesForApprovalRuleTemplate'
    )


class XAmzTarget48(Enum):
    CodeCommit_20150413_ListTagsForResource = 'CodeCommit_20150413.ListTagsForResource'


class XAmzTarget49(Enum):
    CodeCommit_20150413_MergeBranchesByFastForward = (
        'CodeCommit_20150413.MergeBranchesByFastForward'
    )


class XAmzTarget50(Enum):
    CodeCommit_20150413_MergeBranchesBySquash = (
        'CodeCommit_20150413.MergeBranchesBySquash'
    )


class XAmzTarget51(Enum):
    CodeCommit_20150413_MergeBranchesByThreeWay = (
        'CodeCommit_20150413.MergeBranchesByThreeWay'
    )


class XAmzTarget52(Enum):
    CodeCommit_20150413_MergePullRequestByFastForward = (
        'CodeCommit_20150413.MergePullRequestByFastForward'
    )


class XAmzTarget53(Enum):
    CodeCommit_20150413_MergePullRequestBySquash = (
        'CodeCommit_20150413.MergePullRequestBySquash'
    )


class XAmzTarget54(Enum):
    CodeCommit_20150413_MergePullRequestByThreeWay = (
        'CodeCommit_20150413.MergePullRequestByThreeWay'
    )


class XAmzTarget55(Enum):
    CodeCommit_20150413_OverridePullRequestApprovalRules = (
        'CodeCommit_20150413.OverridePullRequestApprovalRules'
    )


class XAmzTarget56(Enum):
    CodeCommit_20150413_PostCommentForComparedCommit = (
        'CodeCommit_20150413.PostCommentForComparedCommit'
    )


class XAmzTarget57(Enum):
    CodeCommit_20150413_PostCommentForPullRequest = (
        'CodeCommit_20150413.PostCommentForPullRequest'
    )


class XAmzTarget58(Enum):
    CodeCommit_20150413_PostCommentReply = 'CodeCommit_20150413.PostCommentReply'


class XAmzTarget59(Enum):
    CodeCommit_20150413_PutCommentReaction = 'CodeCommit_20150413.PutCommentReaction'


class XAmzTarget60(Enum):
    CodeCommit_20150413_PutFile = 'CodeCommit_20150413.PutFile'


class XAmzTarget61(Enum):
    CodeCommit_20150413_PutRepositoryTriggers = (
        'CodeCommit_20150413.PutRepositoryTriggers'
    )


class XAmzTarget62(Enum):
    CodeCommit_20150413_TagResource = 'CodeCommit_20150413.TagResource'


class XAmzTarget63(Enum):
    CodeCommit_20150413_TestRepositoryTriggers = (
        'CodeCommit_20150413.TestRepositoryTriggers'
    )


class XAmzTarget64(Enum):
    CodeCommit_20150413_UntagResource = 'CodeCommit_20150413.UntagResource'


class XAmzTarget65(Enum):
    CodeCommit_20150413_UpdateApprovalRuleTemplateContent = (
        'CodeCommit_20150413.UpdateApprovalRuleTemplateContent'
    )


class XAmzTarget66(Enum):
    CodeCommit_20150413_UpdateApprovalRuleTemplateDescription = (
        'CodeCommit_20150413.UpdateApprovalRuleTemplateDescription'
    )


class XAmzTarget67(Enum):
    CodeCommit_20150413_UpdateApprovalRuleTemplateName = (
        'CodeCommit_20150413.UpdateApprovalRuleTemplateName'
    )


class XAmzTarget68(Enum):
    CodeCommit_20150413_UpdateComment = 'CodeCommit_20150413.UpdateComment'


class XAmzTarget69(Enum):
    CodeCommit_20150413_UpdateDefaultBranch = 'CodeCommit_20150413.UpdateDefaultBranch'


class XAmzTarget70(Enum):
    CodeCommit_20150413_UpdatePullRequestApprovalRuleContent = (
        'CodeCommit_20150413.UpdatePullRequestApprovalRuleContent'
    )


class XAmzTarget71(Enum):
    CodeCommit_20150413_UpdatePullRequestApprovalState = (
        'CodeCommit_20150413.UpdatePullRequestApprovalState'
    )


class XAmzTarget72(Enum):
    CodeCommit_20150413_UpdatePullRequestDescription = (
        'CodeCommit_20150413.UpdatePullRequestDescription'
    )


class XAmzTarget73(Enum):
    CodeCommit_20150413_UpdatePullRequestStatus = (
        'CodeCommit_20150413.UpdatePullRequestStatus'
    )


class XAmzTarget74(Enum):
    CodeCommit_20150413_UpdatePullRequestTitle = (
        'CodeCommit_20150413.UpdatePullRequestTitle'
    )


class XAmzTarget75(Enum):
    CodeCommit_20150413_UpdateRepositoryDescription = (
        'CodeCommit_20150413.UpdateRepositoryDescription'
    )


class XAmzTarget76(Enum):
    CodeCommit_20150413_UpdateRepositoryName = (
        'CodeCommit_20150413.UpdateRepositoryName'
    )


class Approval(BaseModel):
    approvalState: Optional[ApprovalState] = None
    userArn: Optional[Arn] = None


class ApprovalList(RootModel[List[Approval]]):
    root: List[Approval]


class ApprovalRule(BaseModel):
    approvalRuleContent: Optional[ApprovalRuleContent] = None
    approvalRuleId: Optional[ApprovalRuleId] = None
    approvalRuleName: Optional[ApprovalRuleName] = None
    creationDate: Optional[CreationDate] = None
    lastModifiedDate: Optional[LastModifiedDate] = None
    lastModifiedUser: Optional[Arn] = None
    originApprovalRuleTemplate: Optional[OriginApprovalRuleTemplate] = None
    ruleContentSha256: Optional[RuleContentSha256] = None


class ApprovalRuleEventMetadata(BaseModel):
    approvalRuleContent: Optional[ApprovalRuleContent] = None
    approvalRuleId: Optional[ApprovalRuleId] = None
    approvalRuleName: Optional[ApprovalRuleName] = None


class ApprovalRuleOverriddenEventMetadata(BaseModel):
    overrideStatus: Optional[OverrideStatus] = None
    revisionId: Optional[RevisionId] = None


class ApprovalRuleTemplate(BaseModel):
    approvalRuleTemplateContent: Optional[ApprovalRuleTemplateContent] = None
    approvalRuleTemplateDescription: Optional[ApprovalRuleTemplateDescription] = None
    approvalRuleTemplateId: Optional[ApprovalRuleTemplateId] = None
    approvalRuleTemplateName: Optional[ApprovalRuleTemplateName] = None
    creationDate: Optional[CreationDate] = None
    lastModifiedDate: Optional[LastModifiedDate] = None
    lastModifiedUser: Optional[Arn] = None
    ruleContentSha256: Optional[RuleContentSha256] = None


class ApprovalRulesList(RootModel[List[ApprovalRule]]):
    root: List[ApprovalRule]


class ApprovalStateChangedEventMetadata(BaseModel):
    approvalStatus: Optional[ApprovalState] = None
    revisionId: Optional[RevisionId] = None


class AssociateApprovalRuleTemplateWithRepositoryInput(BaseModel):
    approvalRuleTemplateName: ApprovalRuleTemplateName
    repositoryName: RepositoryName


class BatchAssociateApprovalRuleTemplateWithRepositoriesError(BaseModel):
    errorCode: Optional[ErrorCode] = None
    errorMessage: Optional[ErrorMessage] = None
    repositoryName: Optional[RepositoryName] = None


class BatchAssociateApprovalRuleTemplateWithRepositoriesErrorsList(
    RootModel[List[BatchAssociateApprovalRuleTemplateWithRepositoriesError]]
):
    root: List[BatchAssociateApprovalRuleTemplateWithRepositoriesError]


class BatchAssociateApprovalRuleTemplateWithRepositoriesInput(BaseModel):
    approvalRuleTemplateName: ApprovalRuleTemplateName
    repositoryNames: RepositoryNameList


class BatchAssociateApprovalRuleTemplateWithRepositoriesOutput(BaseModel):
    associatedRepositoryNames: RepositoryNameList
    errors: BatchAssociateApprovalRuleTemplateWithRepositoriesErrorsList


class BatchDescribeMergeConflictsError(BaseModel):
    exceptionName: ExceptionName
    filePath: Path
    message: Message


class BatchDescribeMergeConflictsErrors(
    RootModel[List[BatchDescribeMergeConflictsError]]
):
    root: List[BatchDescribeMergeConflictsError]


class BatchDisassociateApprovalRuleTemplateFromRepositoriesError(BaseModel):
    errorCode: Optional[ErrorCode] = None
    errorMessage: Optional[ErrorMessage] = None
    repositoryName: Optional[RepositoryName] = None


class BatchDisassociateApprovalRuleTemplateFromRepositoriesErrorsList(
    RootModel[List[BatchDisassociateApprovalRuleTemplateFromRepositoriesError]]
):
    root: List[BatchDisassociateApprovalRuleTemplateFromRepositoriesError]


class BatchDisassociateApprovalRuleTemplateFromRepositoriesInput(BaseModel):
    approvalRuleTemplateName: ApprovalRuleTemplateName
    repositoryNames: RepositoryNameList


class BatchDisassociateApprovalRuleTemplateFromRepositoriesOutput(BaseModel):
    disassociatedRepositoryNames: RepositoryNameList
    errors: BatchDisassociateApprovalRuleTemplateFromRepositoriesErrorsList


class BatchGetCommitsError(BaseModel):
    commitId: Optional[ObjectId] = None
    errorCode: Optional[ErrorCode] = None
    errorMessage: Optional[ErrorMessage] = None


class BatchGetCommitsErrorsList(RootModel[List[BatchGetCommitsError]]):
    root: List[BatchGetCommitsError]


class BatchGetRepositoriesInput(BaseModel):
    repositoryNames: RepositoryNameList


class BlobMetadata(BaseModel):
    blobId: Optional[ObjectId] = None
    mode: Optional[Mode] = None
    path: Optional[Path] = None


class BranchInfo(BaseModel):
    branchName: Optional[BranchName] = None
    commitId: Optional[CommitId] = None


class CallerReactions(RootModel[List[ReactionValue]]):
    root: List[ReactionValue]


class Comment(BaseModel):
    authorArn: Optional[Arn] = None
    callerReactions: Optional[CallerReactions] = None
    clientRequestToken: Optional[ClientRequestToken] = None
    commentId: Optional[CommentId] = None
    content: Optional[Content] = None
    creationDate: Optional[CreationDate] = None
    deleted: Optional[IsCommentDeleted] = None
    inReplyTo: Optional[CommentId] = None
    lastModifiedDate: Optional[LastModifiedDate] = None
    reactionCounts: Optional[ReactionCountsMap] = None


class Comments(RootModel[List[Comment]]):
    root: List[Comment]


class Commit(BaseModel):
    additionalData: Optional[AdditionalData] = None
    author: Optional[UserInfo] = None
    commitId: Optional[ObjectId] = None
    committer: Optional[UserInfo] = None
    message: Optional[Message] = None
    parents: Optional[ParentList] = None
    treeId: Optional[ObjectId] = None


class CommitIdsInputList(RootModel[List[ObjectId]]):
    root: List[ObjectId]


class CommitObjectsList(RootModel[List[Commit]]):
    root: List[Commit]


class ConflictMetadata(BaseModel):
    contentConflict: Optional[IsContentConflict] = None
    fileModeConflict: Optional[IsFileModeConflict] = None
    fileModes: Optional[FileModes] = None
    filePath: Optional[Path] = None
    fileSizes: Optional[FileSizes] = None
    isBinaryFile: Optional[IsBinaryFile] = None
    mergeOperations: Optional[MergeOperations] = None
    numberOfConflicts: Optional[NumberOfConflicts] = None
    objectTypeConflict: Optional[IsObjectTypeConflict] = None
    objectTypes: Optional[ObjectTypes] = None


class ConflictMetadataList(RootModel[List[ConflictMetadata]]):
    root: List[ConflictMetadata]


class CreateApprovalRuleTemplateOutput(BaseModel):
    approvalRuleTemplate: ApprovalRuleTemplate


class CreateBranchInput(BaseModel):
    branchName: BranchName
    commitId: CommitId
    repositoryName: RepositoryName


class CreatePullRequestApprovalRuleInput(BaseModel):
    approvalRuleContent: ApprovalRuleContent
    approvalRuleName: ApprovalRuleName
    pullRequestId: PullRequestId


class CreatePullRequestApprovalRuleOutput(BaseModel):
    approvalRule: ApprovalRule


class CreatePullRequestInput(BaseModel):
    clientRequestToken: Optional[ClientRequestToken] = None
    description: Optional[Description] = None
    targets: TargetList
    title: Title


class CreateRepositoryInput(BaseModel):
    repositoryDescription: Optional[RepositoryDescription] = None
    repositoryName: RepositoryName
    tags: Optional[TagsMap] = None


class CreateUnreferencedMergeCommitOutput(BaseModel):
    commitId: Optional[ObjectId] = None
    treeId: Optional[ObjectId] = None


class DeleteBranchInput(BaseModel):
    branchName: BranchName
    repositoryName: RepositoryName


class DeleteBranchOutput(BaseModel):
    deletedBranch: Optional[BranchInfo] = None


class DeleteCommentContentOutput(BaseModel):
    comment: Optional[Comment] = None


class DeleteFileEntry(BaseModel):
    filePath: Path


class DeleteFileInput(BaseModel):
    branchName: BranchName
    commitMessage: Optional[Message] = None
    email: Optional[Email] = None
    filePath: Path
    keepEmptyFolders: Optional[KeepEmptyFolders] = None
    name: Optional[Name] = None
    parentCommitId: CommitId
    repositoryName: RepositoryName


class DeleteFileOutput(BaseModel):
    blobId: ObjectId
    commitId: ObjectId
    filePath: Path
    treeId: ObjectId


class DeletePullRequestApprovalRuleInput(BaseModel):
    approvalRuleName: ApprovalRuleName
    pullRequestId: PullRequestId


class DeleteRepositoryInput(BaseModel):
    repositoryName: RepositoryName


class DeleteRepositoryOutput(BaseModel):
    repositoryId: Optional[RepositoryId] = None


class DescribeMergeConflictsInput(BaseModel):
    conflictDetailLevel: Optional[ConflictDetailLevelTypeEnum] = None
    conflictResolutionStrategy: Optional[ConflictResolutionStrategyTypeEnum] = None
    destinationCommitSpecifier: CommitName
    filePath: Path
    maxMergeHunks: Optional[MaxResults] = None
    mergeOption: MergeOptionTypeEnum
    nextToken: Optional[NextToken] = None
    repositoryName: RepositoryName
    sourceCommitSpecifier: CommitName


class DescribePullRequestEventsInput(BaseModel):
    actorArn: Optional[Arn] = None
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[NextToken] = None
    pullRequestEventType: Optional[PullRequestEventType] = None
    pullRequestId: PullRequestId


class Difference(BaseModel):
    afterBlob: Optional[BlobMetadata] = None
    beforeBlob: Optional[BlobMetadata] = None
    changeType: Optional[ChangeTypeEnum] = None


class DifferenceList(RootModel[List[Difference]]):
    root: List[Difference]


class DisassociateApprovalRuleTemplateFromRepositoryInput(BaseModel):
    approvalRuleTemplateName: ApprovalRuleTemplateName
    repositoryName: RepositoryName


class EvaluatePullRequestApprovalRulesInput(BaseModel):
    pullRequestId: PullRequestId
    revisionId: RevisionId


class Evaluation(BaseModel):
    approvalRulesNotSatisfied: Optional[ApprovalRulesNotSatisfiedList] = None
    approvalRulesSatisfied: Optional[ApprovalRulesSatisfiedList] = None
    approved: Optional[Approved] = None
    overridden: Optional[Overridden] = None


class File(BaseModel):
    absolutePath: Optional[Path] = None
    blobId: Optional[ObjectId] = None
    fileMode: Optional[FileModeTypeEnum] = None
    relativePath: Optional[Path] = None


class FileList(RootModel[List[File]]):
    root: List[File]


class FileMetadata(BaseModel):
    absolutePath: Optional[Path] = None
    blobId: Optional[ObjectId] = None
    fileMode: Optional[FileModeTypeEnum] = None


class FilePaths(RootModel[List[Path]]):
    root: List[Path]


class FilesMetadata(RootModel[List[FileMetadata]]):
    root: List[FileMetadata]


class Folder(BaseModel):
    absolutePath: Optional[Path] = None
    relativePath: Optional[Path] = None
    treeId: Optional[ObjectId] = None


class FolderList(RootModel[List[Folder]]):
    root: List[Folder]


class GetApprovalRuleTemplateOutput(BaseModel):
    approvalRuleTemplate: ApprovalRuleTemplate


class GetBlobInput(BaseModel):
    blobId: ObjectId
    repositoryName: RepositoryName


class GetBlobOutput(BaseModel):
    content: Blob


class GetBranchInput(BaseModel):
    branchName: Optional[BranchName] = None
    repositoryName: Optional[RepositoryName] = None


class GetBranchOutput(BaseModel):
    branch: Optional[BranchInfo] = None


class GetCommentOutput(BaseModel):
    comment: Optional[Comment] = None


class GetCommentReactionsInput(BaseModel):
    commentId: CommentId
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[NextToken] = None
    reactionUserArn: Optional[Arn] = None


class GetCommentsForComparedCommitInput(BaseModel):
    afterCommitId: CommitId
    beforeCommitId: Optional[CommitId] = None
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[NextToken] = None
    repositoryName: RepositoryName


class GetCommentsForPullRequestInput(BaseModel):
    afterCommitId: Optional[CommitId] = None
    beforeCommitId: Optional[CommitId] = None
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[NextToken] = None
    pullRequestId: PullRequestId
    repositoryName: Optional[RepositoryName] = None


class GetCommitInput(BaseModel):
    commitId: ObjectId
    repositoryName: RepositoryName


class GetCommitOutput(BaseModel):
    commit: Commit


class GetDifferencesInput(BaseModel):
    MaxResults: Optional[Limit] = None
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    afterCommitSpecifier: CommitName
    afterPath: Optional[Path] = None
    beforeCommitSpecifier: Optional[CommitName] = None
    beforePath: Optional[Path] = None
    repositoryName: RepositoryName


class GetDifferencesOutput(BaseModel):
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    differences: Optional[DifferenceList] = None


class GetFileInput(BaseModel):
    commitSpecifier: Optional[CommitName] = None
    filePath: Path
    repositoryName: RepositoryName


class GetFileOutput(BaseModel):
    blobId: ObjectId
    commitId: ObjectId
    fileContent: FileContent
    fileMode: FileModeTypeEnum
    filePath: Path
    fileSize: ObjectSize


class GetFolderInput(BaseModel):
    commitSpecifier: Optional[CommitName] = None
    folderPath: Path
    repositoryName: RepositoryName


class GetFolderOutput(BaseModel):
    commitId: ObjectId
    files: Optional[FileList] = None
    folderPath: Path
    subFolders: Optional[FolderList] = None
    subModules: Optional[SubModuleList] = None
    symbolicLinks: Optional[SymbolicLinkList] = None
    treeId: Optional[ObjectId] = None


class GetMergeCommitInput(BaseModel):
    conflictDetailLevel: Optional[ConflictDetailLevelTypeEnum] = None
    conflictResolutionStrategy: Optional[ConflictResolutionStrategyTypeEnum] = None
    destinationCommitSpecifier: CommitName
    repositoryName: RepositoryName
    sourceCommitSpecifier: CommitName


class GetMergeCommitOutput(BaseModel):
    baseCommitId: Optional[ObjectId] = None
    destinationCommitId: Optional[ObjectId] = None
    mergedCommitId: Optional[ObjectId] = None
    sourceCommitId: Optional[ObjectId] = None


class GetMergeConflictsInput(BaseModel):
    conflictDetailLevel: Optional[ConflictDetailLevelTypeEnum] = None
    conflictResolutionStrategy: Optional[ConflictResolutionStrategyTypeEnum] = None
    destinationCommitSpecifier: CommitName
    maxConflictFiles: Optional[MaxResults] = None
    mergeOption: MergeOptionTypeEnum
    nextToken: Optional[NextToken] = None
    repositoryName: RepositoryName
    sourceCommitSpecifier: CommitName


class GetMergeConflictsOutput(BaseModel):
    baseCommitId: Optional[ObjectId] = None
    conflictMetadataList: ConflictMetadataList
    destinationCommitId: ObjectId
    mergeable: IsMergeable
    nextToken: Optional[NextToken] = None
    sourceCommitId: ObjectId


class GetMergeOptionsInput(BaseModel):
    conflictDetailLevel: Optional[ConflictDetailLevelTypeEnum] = None
    conflictResolutionStrategy: Optional[ConflictResolutionStrategyTypeEnum] = None
    destinationCommitSpecifier: CommitName
    repositoryName: RepositoryName
    sourceCommitSpecifier: CommitName


class GetMergeOptionsOutput(BaseModel):
    baseCommitId: ObjectId
    destinationCommitId: ObjectId
    mergeOptions: MergeOptions
    sourceCommitId: ObjectId


class GetPullRequestApprovalStatesInput(BaseModel):
    pullRequestId: PullRequestId
    revisionId: RevisionId


class GetPullRequestApprovalStatesOutput(BaseModel):
    approvals: Optional[ApprovalList] = None


class GetPullRequestInput(BaseModel):
    pullRequestId: PullRequestId


class GetPullRequestOverrideStateInput(BaseModel):
    pullRequestId: PullRequestId
    revisionId: RevisionId


class GetPullRequestOverrideStateOutput(BaseModel):
    overridden: Optional[Overridden] = None
    overrider: Optional[Arn] = None


class GetRepositoryInput(BaseModel):
    repositoryName: RepositoryName


class GetRepositoryTriggersInput(BaseModel):
    repositoryName: RepositoryName


class ListApprovalRuleTemplatesInput(BaseModel):
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[NextToken] = None


class ListApprovalRuleTemplatesOutput(BaseModel):
    approvalRuleTemplateNames: Optional[ApprovalRuleTemplateNameList] = None
    nextToken: Optional[NextToken] = None


class ListAssociatedApprovalRuleTemplatesForRepositoryInput(BaseModel):
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[NextToken] = None
    repositoryName: RepositoryName


class ListAssociatedApprovalRuleTemplatesForRepositoryOutput(BaseModel):
    approvalRuleTemplateNames: Optional[ApprovalRuleTemplateNameList] = None
    nextToken: Optional[NextToken] = None


class ListBranchesInput(BaseModel):
    nextToken: Optional[NextToken] = None
    repositoryName: RepositoryName


class ListBranchesOutput(BaseModel):
    branches: Optional[BranchNameList] = None
    nextToken: Optional[NextToken] = None


class ListPullRequestsInput(BaseModel):
    authorArn: Optional[Arn] = None
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[NextToken] = None
    pullRequestStatus: Optional[PullRequestStatusEnum] = None
    repositoryName: RepositoryName


class ListPullRequestsOutput(BaseModel):
    nextToken: Optional[NextToken] = None
    pullRequestIds: PullRequestIdList


class ListRepositoriesForApprovalRuleTemplateInput(BaseModel):
    approvalRuleTemplateName: ApprovalRuleTemplateName
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[NextToken] = None


class ListRepositoriesForApprovalRuleTemplateOutput(BaseModel):
    nextToken: Optional[NextToken] = None
    repositoryNames: Optional[RepositoryNameList] = None


class ListRepositoriesInput(BaseModel):
    nextToken: Optional[NextToken] = None
    order: Optional[OrderEnum] = None
    sortBy: Optional[SortByEnum] = None


class ListRepositoriesOutput(BaseModel):
    nextToken: Optional[NextToken] = None
    repositories: Optional[RepositoryNameIdPairList] = None


class ListTagsForResourceInput(BaseModel):
    nextToken: Optional[NextToken] = None
    resourceArn: ResourceArn


class ListTagsForResourceOutput(BaseModel):
    nextToken: Optional[NextToken] = None
    tags: Optional[TagsMap] = None


class Location(BaseModel):
    filePath: Optional[Path] = None
    filePosition: Optional[Position] = None
    relativeFileVersion: Optional[RelativeFileVersionEnum] = None


class MergeBranchesByFastForwardInput(BaseModel):
    destinationCommitSpecifier: CommitName
    repositoryName: RepositoryName
    sourceCommitSpecifier: CommitName
    targetBranch: Optional[BranchName] = None


class MergeBranchesByFastForwardOutput(BaseModel):
    commitId: Optional[ObjectId] = None
    treeId: Optional[ObjectId] = None


class MergeBranchesBySquashOutput(BaseModel):
    commitId: Optional[ObjectId] = None
    treeId: Optional[ObjectId] = None


class MergeBranchesByThreeWayOutput(BaseModel):
    commitId: Optional[ObjectId] = None
    treeId: Optional[ObjectId] = None


class MergeHunk(BaseModel):
    base: Optional[MergeHunkDetail] = None
    destination: Optional[MergeHunkDetail] = None
    isConflict: Optional[IsHunkConflict] = None
    source: Optional[MergeHunkDetail] = None


class MergeHunks(RootModel[List[MergeHunk]]):
    root: List[MergeHunk]


class MergeMetadata(BaseModel):
    isMerged: Optional[IsMerged] = None
    mergeCommitId: Optional[CommitId] = None
    mergeOption: Optional[MergeOptionTypeEnum] = None
    mergedBy: Optional[Arn] = None


class MergePullRequestByFastForwardInput(BaseModel):
    pullRequestId: PullRequestId
    repositoryName: RepositoryName
    sourceCommitId: Optional[ObjectId] = None


class OverridePullRequestApprovalRulesInput(BaseModel):
    overrideStatus: OverrideStatus
    pullRequestId: PullRequestId
    revisionId: RevisionId


class PostCommentForComparedCommitInput(BaseModel):
    afterCommitId: CommitId
    beforeCommitId: Optional[CommitId] = None
    clientRequestToken: Optional[ClientRequestToken] = None
    content: Content
    location: Optional[Location] = None
    repositoryName: RepositoryName


class PostCommentForComparedCommitOutput(BaseModel):
    afterBlobId: Optional[ObjectId] = None
    afterCommitId: Optional[CommitId] = None
    beforeBlobId: Optional[ObjectId] = None
    beforeCommitId: Optional[CommitId] = None
    comment: Optional[Comment] = None
    location: Optional[Location] = None
    repositoryName: Optional[RepositoryName] = None


class PostCommentForPullRequestInput(BaseModel):
    afterCommitId: CommitId
    beforeCommitId: CommitId
    clientRequestToken: Optional[ClientRequestToken] = None
    content: Content
    location: Optional[Location] = None
    pullRequestId: PullRequestId
    repositoryName: RepositoryName


class PostCommentForPullRequestOutput(BaseModel):
    afterBlobId: Optional[ObjectId] = None
    afterCommitId: Optional[CommitId] = None
    beforeBlobId: Optional[ObjectId] = None
    beforeCommitId: Optional[CommitId] = None
    comment: Optional[Comment] = None
    location: Optional[Location] = None
    pullRequestId: Optional[PullRequestId] = None
    repositoryName: Optional[RepositoryName] = None


class PostCommentReplyOutput(BaseModel):
    comment: Optional[Comment] = None


class PullRequestCreatedEventMetadata(BaseModel):
    destinationCommitId: Optional[CommitId] = None
    mergeBase: Optional[CommitId] = None
    repositoryName: Optional[RepositoryName] = None
    sourceCommitId: Optional[CommitId] = None


class PullRequestMergedStateChangedEventMetadata(BaseModel):
    destinationReference: Optional[ReferenceName] = None
    mergeMetadata: Optional[MergeMetadata] = None
    repositoryName: Optional[RepositoryName] = None


class PullRequestSourceReferenceUpdatedEventMetadata(BaseModel):
    afterCommitId: Optional[CommitId] = None
    beforeCommitId: Optional[CommitId] = None
    mergeBase: Optional[CommitId] = None
    repositoryName: Optional[RepositoryName] = None


class PullRequestStatusChangedEventMetadata(BaseModel):
    pullRequestStatus: Optional[PullRequestStatusEnum] = None


class PullRequestTarget(BaseModel):
    destinationCommit: Optional[CommitId] = None
    destinationReference: Optional[ReferenceName] = None
    mergeBase: Optional[CommitId] = None
    mergeMetadata: Optional[MergeMetadata] = None
    repositoryName: Optional[RepositoryName] = None
    sourceCommit: Optional[CommitId] = None
    sourceReference: Optional[ReferenceName] = None


class PullRequestTargetList(RootModel[List[PullRequestTarget]]):
    root: List[PullRequestTarget]


class PutCommentReactionInput(BaseModel):
    commentId: CommentId
    reactionValue: ReactionValue


class PutFileEntry(BaseModel):
    fileContent: Optional[FileContent] = None
    fileMode: Optional[FileModeTypeEnum] = None
    filePath: Path
    sourceFile: Optional[SourceFileSpecifier] = None


class PutFileInput(BaseModel):
    branchName: BranchName
    commitMessage: Optional[Message] = None
    email: Optional[Email] = None
    fileContent: FileContent
    fileMode: Optional[FileModeTypeEnum] = None
    filePath: Path
    name: Optional[Name] = None
    parentCommitId: Optional[CommitId] = None
    repositoryName: RepositoryName


class PutRepositoryTriggersOutput(BaseModel):
    configurationId: Optional[RepositoryTriggersConfigurationId] = None


class ReactionForComment(BaseModel):
    reaction: Optional[ReactionValueFormats] = None
    reactionUsers: Optional[ReactionUsersList] = None
    reactionsFromDeletedUsersCount: Optional[Count] = None


class ReactionsForCommentList(RootModel[List[ReactionForComment]]):
    root: List[ReactionForComment]


class ReplaceContentEntry(BaseModel):
    content: Optional[FileContent] = None
    fileMode: Optional[FileModeTypeEnum] = None
    filePath: Path
    replacementType: ReplacementTypeEnum


class RepositoryMetadata(BaseModel):
    Arn_1: Optional[Arn] = Field(None, alias='Arn')
    accountId: Optional[AccountId] = None
    cloneUrlHttp: Optional[CloneUrlHttp] = None
    cloneUrlSsh: Optional[CloneUrlSsh] = None
    creationDate: Optional[CreationDate] = None
    defaultBranch: Optional[BranchName] = None
    lastModifiedDate: Optional[LastModifiedDate] = None
    repositoryDescription: Optional[RepositoryDescription] = None
    repositoryId: Optional[RepositoryId] = None
    repositoryName: Optional[RepositoryName] = None


class RepositoryMetadataList(RootModel[List[RepositoryMetadata]]):
    root: List[RepositoryMetadata]


class RepositoryTrigger(BaseModel):
    branches: Optional[BranchNameList] = None
    customData: Optional[RepositoryTriggerCustomData] = None
    destinationArn: Arn
    events: RepositoryTriggerEventList
    name: RepositoryTriggerName


class RepositoryTriggerExecutionFailure(BaseModel):
    failureMessage: Optional[RepositoryTriggerExecutionFailureMessage] = None
    trigger: Optional[RepositoryTriggerName] = None


class RepositoryTriggerExecutionFailureList(
    RootModel[List[RepositoryTriggerExecutionFailure]]
):
    root: List[RepositoryTriggerExecutionFailure]


class RepositoryTriggersList(RootModel[List[RepositoryTrigger]]):
    root: List[RepositoryTrigger]


class SetFileModeEntries(RootModel[List[SetFileModeEntry]]):
    root: List[SetFileModeEntry]


class TagResourceInput(BaseModel):
    resourceArn: ResourceArn
    tags: TagsMap


class TestRepositoryTriggersInput(BaseModel):
    repositoryName: RepositoryName
    triggers: RepositoryTriggersList


class TestRepositoryTriggersOutput(BaseModel):
    failedExecutions: Optional[RepositoryTriggerExecutionFailureList] = None
    successfulExecutions: Optional[RepositoryTriggerNameList] = None


class UpdateApprovalRuleTemplateContentOutput(BaseModel):
    approvalRuleTemplate: ApprovalRuleTemplate


class UpdateApprovalRuleTemplateDescriptionOutput(BaseModel):
    approvalRuleTemplate: ApprovalRuleTemplate


class UpdateApprovalRuleTemplateNameOutput(BaseModel):
    approvalRuleTemplate: ApprovalRuleTemplate


class UpdateCommentOutput(BaseModel):
    comment: Optional[Comment] = None


class UpdatePullRequestApprovalRuleContentOutput(BaseModel):
    approvalRule: ApprovalRule


class BatchDescribeMergeConflictsInput(BaseModel):
    conflictDetailLevel: Optional[ConflictDetailLevelTypeEnum] = None
    conflictResolutionStrategy: Optional[ConflictResolutionStrategyTypeEnum] = None
    destinationCommitSpecifier: CommitName
    filePaths: Optional[FilePaths] = None
    maxConflictFiles: Optional[MaxResults] = None
    maxMergeHunks: Optional[MaxResults] = None
    mergeOption: MergeOptionTypeEnum
    nextToken: Optional[NextToken] = None
    repositoryName: RepositoryName
    sourceCommitSpecifier: CommitName


class BatchGetCommitsInput(BaseModel):
    commitIds: CommitIdsInputList
    repositoryName: RepositoryName


class BatchGetCommitsOutput(BaseModel):
    commits: Optional[CommitObjectsList] = None
    errors: Optional[BatchGetCommitsErrorsList] = None


class BatchGetRepositoriesOutput(BaseModel):
    repositories: Optional[RepositoryMetadataList] = None
    repositoriesNotFound: Optional[RepositoryNotFoundList] = None


class CommentsForComparedCommit(BaseModel):
    afterBlobId: Optional[ObjectId] = None
    afterCommitId: Optional[CommitId] = None
    beforeBlobId: Optional[ObjectId] = None
    beforeCommitId: Optional[CommitId] = None
    comments: Optional[Comments] = None
    location: Optional[Location] = None
    repositoryName: Optional[RepositoryName] = None


class CommentsForComparedCommitData(RootModel[List[CommentsForComparedCommit]]):
    root: List[CommentsForComparedCommit]


class CommentsForPullRequest(BaseModel):
    afterBlobId: Optional[ObjectId] = None
    afterCommitId: Optional[CommitId] = None
    beforeBlobId: Optional[ObjectId] = None
    beforeCommitId: Optional[CommitId] = None
    comments: Optional[Comments] = None
    location: Optional[Location] = None
    pullRequestId: Optional[PullRequestId] = None
    repositoryName: Optional[RepositoryName] = None


class CommentsForPullRequestData(RootModel[List[CommentsForPullRequest]]):
    root: List[CommentsForPullRequest]


class Conflict(BaseModel):
    conflictMetadata: Optional[ConflictMetadata] = None
    mergeHunks: Optional[MergeHunks] = None


class Conflicts(RootModel[List[Conflict]]):
    root: List[Conflict]


class CreateCommitOutput(BaseModel):
    commitId: Optional[ObjectId] = None
    filesAdded: Optional[FilesMetadata] = None
    filesDeleted: Optional[FilesMetadata] = None
    filesUpdated: Optional[FilesMetadata] = None
    treeId: Optional[ObjectId] = None


class CreateRepositoryOutput(BaseModel):
    repositoryMetadata: Optional[RepositoryMetadata] = None


class DeleteFileEntries(RootModel[List[DeleteFileEntry]]):
    root: List[DeleteFileEntry]


class DescribeMergeConflictsOutput(BaseModel):
    baseCommitId: Optional[ObjectId] = None
    conflictMetadata: ConflictMetadata
    destinationCommitId: ObjectId
    mergeHunks: MergeHunks
    nextToken: Optional[NextToken] = None
    sourceCommitId: ObjectId


class EvaluatePullRequestApprovalRulesOutput(BaseModel):
    evaluation: Evaluation


class GetCommentReactionsOutput(BaseModel):
    nextToken: Optional[NextToken] = None
    reactionsForComment: ReactionsForCommentList


class GetCommentsForComparedCommitOutput(BaseModel):
    commentsForComparedCommitData: Optional[CommentsForComparedCommitData] = None
    nextToken: Optional[NextToken] = None


class GetCommentsForPullRequestOutput(BaseModel):
    commentsForPullRequestData: Optional[CommentsForPullRequestData] = None
    nextToken: Optional[NextToken] = None


class GetRepositoryOutput(BaseModel):
    repositoryMetadata: Optional[RepositoryMetadata] = None


class GetRepositoryTriggersOutput(BaseModel):
    configurationId: Optional[RepositoryTriggersConfigurationId] = None
    triggers: Optional[RepositoryTriggersList] = None


class PullRequest(BaseModel):
    approvalRules: Optional[ApprovalRulesList] = None
    authorArn: Optional[Arn] = None
    clientRequestToken: Optional[ClientRequestToken] = None
    creationDate: Optional[CreationDate] = None
    description: Optional[Description] = None
    lastActivityDate: Optional[LastModifiedDate] = None
    pullRequestId: Optional[PullRequestId] = None
    pullRequestStatus: Optional[PullRequestStatusEnum] = None
    pullRequestTargets: Optional[PullRequestTargetList] = None
    revisionId: Optional[RevisionId] = None
    title: Optional[Title] = None


class PullRequestEvent(BaseModel):
    actorArn: Optional[Arn] = None
    approvalRuleEventMetadata: Optional[ApprovalRuleEventMetadata] = None
    approvalRuleOverriddenEventMetadata: Optional[
        ApprovalRuleOverriddenEventMetadata
    ] = None
    approvalStateChangedEventMetadata: Optional[ApprovalStateChangedEventMetadata] = (
        None
    )
    eventDate: Optional[EventDate] = None
    pullRequestCreatedEventMetadata: Optional[PullRequestCreatedEventMetadata] = None
    pullRequestEventType: Optional[PullRequestEventType] = None
    pullRequestId: Optional[PullRequestId] = None
    pullRequestMergedStateChangedEventMetadata: Optional[
        PullRequestMergedStateChangedEventMetadata
    ] = None
    pullRequestSourceReferenceUpdatedEventMetadata: Optional[
        PullRequestSourceReferenceUpdatedEventMetadata
    ] = None
    pullRequestStatusChangedEventMetadata: Optional[
        PullRequestStatusChangedEventMetadata
    ] = None


class PullRequestEventList(RootModel[List[PullRequestEvent]]):
    root: List[PullRequestEvent]


class PutFileEntries(RootModel[List[PutFileEntry]]):
    root: List[PutFileEntry]


class PutRepositoryTriggersInput(BaseModel):
    repositoryName: RepositoryName
    triggers: RepositoryTriggersList


class ReplaceContentEntries(RootModel[List[ReplaceContentEntry]]):
    root: List[ReplaceContentEntry]


class UpdatePullRequestDescriptionOutput(BaseModel):
    pullRequest: PullRequest


class UpdatePullRequestStatusOutput(BaseModel):
    pullRequest: PullRequest


class UpdatePullRequestTitleOutput(BaseModel):
    pullRequest: PullRequest


class BatchDescribeMergeConflictsOutput(BaseModel):
    baseCommitId: Optional[ObjectId] = None
    conflicts: Conflicts
    destinationCommitId: ObjectId
    errors: Optional[BatchDescribeMergeConflictsErrors] = None
    nextToken: Optional[NextToken] = None
    sourceCommitId: ObjectId


class ConflictResolution(BaseModel):
    deleteFiles: Optional[DeleteFileEntries] = None
    replaceContents: Optional[ReplaceContentEntries] = None
    setFileModes: Optional[SetFileModeEntries] = None


class CreateCommitInput(BaseModel):
    authorName: Optional[Name] = None
    branchName: BranchName
    commitMessage: Optional[Message] = None
    deleteFiles: Optional[DeleteFileEntries] = None
    email: Optional[Email] = None
    keepEmptyFolders: Optional[KeepEmptyFolders] = None
    parentCommitId: Optional[CommitId] = None
    putFiles: Optional[PutFileEntries] = None
    repositoryName: RepositoryName
    setFileModes: Optional[SetFileModeEntries] = None


class CreatePullRequestOutput(BaseModel):
    pullRequest: PullRequest


class CreateUnreferencedMergeCommitInput(BaseModel):
    authorName: Optional[Name] = None
    commitMessage: Optional[Message] = None
    conflictDetailLevel: Optional[ConflictDetailLevelTypeEnum] = None
    conflictResolution: Optional[ConflictResolution] = None
    conflictResolutionStrategy: Optional[ConflictResolutionStrategyTypeEnum] = None
    destinationCommitSpecifier: CommitName
    email: Optional[Email] = None
    keepEmptyFolders: Optional[KeepEmptyFolders] = None
    mergeOption: MergeOptionTypeEnum
    repositoryName: RepositoryName
    sourceCommitSpecifier: CommitName


class DescribePullRequestEventsOutput(BaseModel):
    nextToken: Optional[NextToken] = None
    pullRequestEvents: PullRequestEventList


class GetPullRequestOutput(BaseModel):
    pullRequest: PullRequest


class MergeBranchesBySquashInput(BaseModel):
    authorName: Optional[Name] = None
    commitMessage: Optional[Message] = None
    conflictDetailLevel: Optional[ConflictDetailLevelTypeEnum] = None
    conflictResolution: Optional[ConflictResolution] = None
    conflictResolutionStrategy: Optional[ConflictResolutionStrategyTypeEnum] = None
    destinationCommitSpecifier: CommitName
    email: Optional[Email] = None
    keepEmptyFolders: Optional[KeepEmptyFolders] = None
    repositoryName: RepositoryName
    sourceCommitSpecifier: CommitName
    targetBranch: Optional[BranchName] = None


class MergeBranchesByThreeWayInput(BaseModel):
    authorName: Optional[Name] = None
    commitMessage: Optional[Message] = None
    conflictDetailLevel: Optional[ConflictDetailLevelTypeEnum] = None
    conflictResolution: Optional[ConflictResolution] = None
    conflictResolutionStrategy: Optional[ConflictResolutionStrategyTypeEnum] = None
    destinationCommitSpecifier: CommitName
    email: Optional[Email] = None
    keepEmptyFolders: Optional[KeepEmptyFolders] = None
    repositoryName: RepositoryName
    sourceCommitSpecifier: CommitName
    targetBranch: Optional[BranchName] = None


class MergePullRequestByFastForwardOutput(BaseModel):
    pullRequest: Optional[PullRequest] = None


class MergePullRequestBySquashInput(BaseModel):
    authorName: Optional[Name] = None
    commitMessage: Optional[Message] = None
    conflictDetailLevel: Optional[ConflictDetailLevelTypeEnum] = None
    conflictResolution: Optional[ConflictResolution] = None
    conflictResolutionStrategy: Optional[ConflictResolutionStrategyTypeEnum] = None
    email: Optional[Email] = None
    keepEmptyFolders: Optional[KeepEmptyFolders] = None
    pullRequestId: PullRequestId
    repositoryName: RepositoryName
    sourceCommitId: Optional[ObjectId] = None


class MergePullRequestBySquashOutput(BaseModel):
    pullRequest: Optional[PullRequest] = None


class MergePullRequestByThreeWayInput(BaseModel):
    authorName: Optional[Name] = None
    commitMessage: Optional[Message] = None
    conflictDetailLevel: Optional[ConflictDetailLevelTypeEnum] = None
    conflictResolution: Optional[ConflictResolution] = None
    conflictResolutionStrategy: Optional[ConflictResolutionStrategyTypeEnum] = None
    email: Optional[Email] = None
    keepEmptyFolders: Optional[KeepEmptyFolders] = None
    pullRequestId: PullRequestId
    repositoryName: RepositoryName
    sourceCommitId: Optional[ObjectId] = None


class MergePullRequestByThreeWayOutput(BaseModel):
    pullRequest: Optional[PullRequest] = None
